### PR TITLE
fixed adjoint_EVAL_D

### PR DESCRIPTION
**Pull request by andresrossb**
fixed adjoint_EVAL_D. It now also works with multiple properties. Needs testing.

### CODE REVIEW

**Comment by cortner** [comment]
I'm nervous about this branch - it seems this is based on a 0.12 version? How did that happen? A lot has happened since then ...

**Comment by cortner** [comment]
after merging in main, all tests now pass. Can you take another look to see what changed?

**Comment by cortner** [comment]
Andres: "I finished the test for the adjoint in ACE. It is now ready to merge. I tested it against grad_params_config for single property, which I understand has tests elsewhere"

**Comment by cortner** [comment]
This has a few significant changes/additions so I want to take a close look before merging. I hope that's ok

**Comment by cortner** [comment]
@andresrossb  -- my memory is we agreed to add some tests before merging? Is that correct?

**Comment by andresrossb** [comment]
> @andresrossb -- my memory is we agreed to add some tests before merging? Is that correct?

yes, I also had to do some changes to the evaluation function and genmul! so I think it would be better to wait until we have a discussion about it. I implemented the adjoint_EVAL_D test, but I'm still missing the loss function test.

**Comment by cortner** [comment]
looking good. I think we need a review and a cleanup, then test that all this works with you ACEflux codes and then we are ready to merge?

**Comment by cortner** [comment]
!! ready to go finally !!

**Pull request merged**
