### PR TITLE
Equiv

### PR DESCRIPTION
**Pull request by MatthiasSachs**
First working version for EuclidianVector-basis

Relevant tests are provided in test/test_symmbasis-equiv.jl

The test sets is not yet added to the general test set.

### CODE REVIEW

**Comment by cortner** [comment]
thank you - will start reviewing asap

**Comment by cortner** [comment]
actually, I'm going to start with a request - can you please make the PR to merge into `equiv` and not into `master`?

**Comment by cortner** [comment]
hm.... I'm really confused,. Are you trying to merge `ACEsuit/equiv` into `master` here? I think you need to try and merge `MatthiasSachs/equiv` into `ACEsuit/equiv`.

**Comment by cortner** [comment]
happy easter :)

**Comment by MatthiasSachs** [comment]
happy easter! :) arghh, sorry, I think I will need to create a new pull request. I did not very carefully review into which branch I am attempting to merge it...

**Pull request closed without merging**
