### PR TITLE
Euclidian vector real version enabled

### PR DESCRIPTION
**Pull request by MatthiasSachs**

### CODE REVIEW

**Comment by cortner** [comment]
I'll need to resolve the conflicts, can you please give me push access to your fork?

**Comment by MatthiasSachs** [comment]
ok, will do! But there is one issue with the invariant properties now. I will fix that and update the pull request.

Best,
Matthias

**Comment by cortner** [comment]
please wait a minute- I'm about to push some changes

**Comment by cortner** [comment]
I just had to update the FIO codes for symmetric basis because of the new parameter.

**Comment by cortner** [comment]
I'll push that to your branch, and then please go ahead and make any other changes you think you need.

**Comment by cortner** [comment]
ok, I merged with my updated v0.10.x branch. I saw the error you noticed. Please go ahead now and update the PR

**Comment by MatthiasSachs** [comment]
OK! I think you have access to my branch, right?

**Comment by cortner** [comment]
ok, I made complex the default, and I put the `real` application in a different place where it avoids another allocation. The main thing still missing is that the gradient of the basis is still complex

**Comment by cortner** [comment]
@MatthiasSachs  please look at my changes, review carefully, rerun tests, and report back that you are happy to merge. I'll then tag new versions of ACEbase and ACE later.

**Pull request merged**
