### PR TITLE
Unification of Generalized CoCos

### PR DESCRIPTION
**Pull request by cortner**
Attempt to unify general coupling coefficients (cocos).

CC @MatthiasSachs @zhanglw0521  If you make changes to this branch, please just push to my fork and the PR will be automatically updated.

### CODE REVIEW

**Comment by cortner** [comment]
sorry I didn't manage to finish the first steps tonight but I'm too tired now. Please feel free to continue from where I left off, but I'll try to continue immediately after school dropoff.

**Comment by cortner** [comment]
Invariants are now working ok - @zhanglw0521 and @MatthiasSachs this is ready for you to start incorporating your versions. However, I still need to move some codes from `rotations` to `symmbasis`.

**Comment by cortner** [comment]
`Invariant` and `EuclideanVector` work in the rewrite. You turn @zhanglw0521  :)

**Comment by cortner** [comment]
@MatthiasSachs @zhanglw0521 I think we have implemented everything we want, and all tests pass now. 
1. Are you happy to merge? 
2. How do you feel about tagging a first release?

**Comment by MatthiasSachs** [comment]
stupid question: "tagging" would mean we give ACE a new version number after merging the coco branch into main?

**Comment by cortner** [comment]
yes but a new `v0.x.y` tag which means we don't yet enforce backward compatibility. Specifically my proposal is 
- tag this as `v0.10.0` and continue to develop ACE as `v0.x.y` with `x >= 10`. 
- keep `v0.9.x` as a "backup" in case we want to break compatibioilty with ACE1 again
- Decide whether to tag `ACE1` as `1.0.0` or leave it as `v0.8.x, v0.9.x`

**Comment by zhanglw0521** [comment]
The main conflict with ACE1 is that we now need to specify the property even when we use the invariant basis only? Do we need to fix the incompatibility in the future or do we just consider `ACE1` and `ACE2` as separate things?

**Comment by cortner** [comment]
ACE2 is so different, there is no compatibility left I think. 

But for practical purposes: we follow semver. (semantic versioning) This means that we may break compatibility if we go from `v0.x.*` to `v0.(x+1).*` and if we go from `vX.*` to `v(X+1).*`. Further, for `vX.y.z` the `z` stands for patches and bug fixes while `y` stands for new features.

**Comment by cortner** [comment]
let's put the versiom discussion elsewhere and focus on merging. I see you are both happy so I'll go ahead with that.

**Pull request merged**
