### PR TITLE
WIP: old bug in basis filter emerging

### PR DESCRIPTION
**Pull request by cortner**
Cf. https://github.com/ACEsuit/ACEatoms.jl/issues/12

CC @zhanglw0521 @MatthiasSachs 

I've only fixed the filter for the Invariant property for now. Please take a look at the others.

### CODE REVIEW

**Review by MatthiasSachs — COMMENTED** [review]
It's not clear to me why ```julia filter(φ::Invariant, b::Array) ``` should return `true` for any basis specification `b` of length =1. Is this correct? Shouldn't we at least exclude specs where `length(b) == 1` and  the `getl(grp, b[1])!=0`?

**Comment by zhanglw0521** [comment]
yup - at least all tests passed except for an O3O3 one.

**Comment by cortner** [comment]
looks ok now - merged and tagged as v0.12.16

**Comment by cortner** [comment]
thank you both

**Pull request merged**
