### PR TITLE
WIP: Performance 1 - Fixing States and 1pBasis Implementations

### PR DESCRIPTION
**Pull request by cortner**
first steps towards making ACE2 performant. There are a few cleanups, starting to put together some benchmarks, but the main contributions here are 
* rewrite the `State` and `DState` implementations to get around a Julia 1.7 bug
* fix a nasty bug in the product1p basis gradient implementation.

The 1p basis evaluation now seems reasonably performant. But unfortunately there is a segfault left that I cannot track down yet. It occurs only with Julia 1.7, not with 1.6, when testing the B1pMultiplier: 
```
[ Info: Testing B1pMultiplier
[ Info: some basic tests

signal (11): Segmentation fault: 11
in expression starting at /Users/ortner/gits/ACE.jl/test/test_multiplier.jl:35
ntuple at ./ntuple.jl:0
unknown function (ip: 0x280d16cdf)
_jl_invoke at /Users/ortner/gits/julia17/src/gf.c:0 [inlined]
jl_apply_generic at /Users/ortner/gits/julia17/src/gf.c:2429
set_spec! at /Users/ortner/gits/ACE.jl/src/product_1pbasis.jl:197
init1pspec! at /Users/ortner/gits/ACE.jl/src/sparsegrids.jl:27
unknown function (ip: 0x280d1599b)
_jl_invoke at /Users/ortner/gits/julia17/src/gf.c:0 [inlined]
jl_apply_generic at /Users/ortner/gits/julia17/src/gf.c:2429
jl_apply at /Users/ortner/gits/julia17/src/./julia.h:1788 [inlined]
do_call at /Users/ortner/gits/julia17/src/interpreter.c:126
eval_body at /Users/ortner/gits/julia17/src/interpreter.c:0
....

```
and the rest is not so interesting. It seems reproducible.

### CODE REVIEW

**Comment by cortner** [comment]
Update ... I'm running into a horrible issue: 
* If I profile with 1.6 instead of 1.7 I lose more than a factor 2 performance. 
* If I profile on our server, I lose a factor 4-5 even when on 1.7. 
It seems that somehow my optimizations work really well but only on my M1 processor?

**Comment by cortner** [comment]
performance on 1.6 is now fixed on my laptop, but still horrendous on our server. This very strange...

**Comment by cortner** [comment]
@andresrossb If you have a free moment, would you be willing to pull this branch and run the `profile/profile_basis.jl' on your laptop?

**Comment by cortner** [comment]
(but seriously, the M1pro is a beast - I get a factor 3 faster performance for the gradients than on the EPYC, which isn't exactly a slouch either...)

**Comment by zhanglw0521** [comment]
> (but seriously, the M1pro is a beast - I get a factor 3 faster performance for the gradients than on the EPYC, which isn't exactly a slouch either...)

Sounds really really attractive...

**Comment by cortner** [comment]
yes, but you'll never get enough M1pro cores to make it a serious contender....

**Comment by cortner** [comment]
Looks like PkgBenchmark is worth integrating into our workflow...
[judge.pdf](https://github.com/ACEsuit/ACE.jl/files/7750049/judge.pdf)

**Comment by cortner** [comment]
this has significant improvements on basis evaluation, so I'll merge and tag before we move on to LinearACEModel.

**Pull request merged**
