### PR TITLE
The Constant (0-correlation)

### PR DESCRIPTION
**Pull request by cortner**
This PR finally brings the constant basis function backs. It's big fat pain, since it requires quite a few special cases, but it may be worth it long term. To deal with the fact that we sometimes want to remove it, I will implement a filter that does so. Good opportunity to test our filtering framework.

This will address #80.

CC @zhanglw0521

### CODE REVIEW

**Comment by cortner** [comment]
@zhanglw0521 is the basis for 0-correlations for the spherical Vector and spherical Matrix. It should depend on the Ls. E.g. for invariants the basis is just [ Invariant(1.0), ] . 

For a euclidean vector, the basis is empty because there is no constant component (can't since it must rotate under rotation). I suspect for spherical the. basis is empty unless all Ls are zero?

**Comment by zhanglw0521** [comment]
> @zhanglw0521 is the basis for 0-correlations for the spherical Vector and spherical Matrix. It should depend on the Ls. E.g. for invariants the basis is just [ Invariant(1.0), ] .
> 
> For a euclidean vector, the basis is empty because there is no constant component (can't since it must rotate under rotation). I suspect for spherical the. basis is empty unless all Ls are zero? But maybe this is wrong for the spherical matrix, when L1+L2 = even?

I even think the constant term could only appear when `L1 = L2` but I would think it through in case I spoke too soon.

**Comment by cortner** [comment]
please take your time to work this out properly

**Comment by cortner** [comment]
this seems ready now except for how to deal with he spherical tensors.

**Comment by zhanglw0521** [comment]
Looks all good to me now. If I made no mistake, the constant terms can't exist for `L1 != L2` as the initial coupling coefficients in this case are zeros. For those `L1 == L2` cases, all possible non zero initial coupling coefficients are the same, hence, only one constant term appears. All these were done and checked by doing an SVD to initial coupling coefficients.

**Comment by zhanglw0521** [comment]
Some necessary tests were added too.

**Comment by cortner** [comment]
thank you - will review asap

**Comment by cortner** [comment]
Liwei - if there is only one such basis function then it must necessarily be a multiple of the identity. Should that be hard-coded instead of the svd reduction that you do, and simply documented somewhere that this is the only constant basis function? Can it be easily proven?

**Comment by cortner** [comment]
Here is where I am nervous: if we took 2D, then rotations commute. So ALL rotation `A` matrices would satisfy `Q * A * Q' = A` for all `Q`. So it is definitely not trivial. Of course my argument doesn't work in 3D since rotations don't commute. Now of course we are in spherical coordinates, so the story changes again ... I'm inclined to believe the result, but can it be proven?

**Comment by zhanglw0521** [comment]
Thanks for pointing out the 2d case. I'd still believe that 3d help us to get rid of nontrivial constant terms - will try to prove it (or disprove...).

**Comment by cortner** [comment]
ok, but maybe I will merge for now and we can make another PR later. At least the code right now looks sensible.

**Comment by zhanglw0521** [comment]
Thanks, I'm happy with that - at least we could stick with the `NoConstant` case so that all functions work as usual.

**Comment by cortner** [comment]
ok, just waiting for tests to finish now then I'll squash and merge.

**Pull request merged**
