### PR TITLE
Replace `degree` with `level` for basis selectors

### PR DESCRIPTION
**Pull request by cortner**
+ a bit of cleanup.

### CODE REVIEW

**Comment by MatthiasSachs** [comment]
Looks good to me! I think this is also now ready to include intersections, right? I can open another pull request of that soon!

**Review by MatthiasSachs — APPROVED** [review]
see comment above

**Comment by cortner** [comment]
Ok, please don't go ahead with the intersections. There is an issue I opened where I'd like to discuss this first.

**Comment by cortner** [comment]
thank you for reviewing

**Pull request merged**
